server:
  port: 7001
spring:
  application:
    name: threadsys
  rabbitmq:
    host: 192.168.2.227
    port: 5672
    username: xyh
    password: wxk888888
    #消息消费者
    listener:
      simple:
        acknowledge-mode: manual #设置消费端手动 ack
        prefetch: 2         #在单个请求中处理的消息个数，他应该大于等于事务数量(unack的最大数量)
        concurrency: 1        #消费者最小数量
        max-concurrency: 10   #消费者最大数量
        retry:
          max-attempts: 3  #重试3次
          enabled: true  # 开启重试
    #消息生产者
    publisher-confirms: true #开启消息确认机制
    publisher-returns: true #支持消息发送失败返回队列
    template:
      mandatory: true #设置为true,消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6001/eureka/
    healthcheck:
      # 开启健康检查（需要spring-boot-starter-actuator依赖）
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 5
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 15
